# Generated by Django 5.2.7 on 2025-10-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade_level',
            new_name='grade',
        ),
    ]
