# Generated by Django 5.2.7 on 2025-10-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_grade_level_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
