# Generated by Django 5.2.7 on 2025-10-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_tag_course_assignment_enrollment_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
