# Generated by Django 5.2.7 on 2025-10-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_lesson_video_url_alter_assignment_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course_image/'),
        ),
    ]
