# Generated by Django 5.2.7 on 2025-10-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='Instructor_id',
        ),
    ]
